# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UiForm(object):
    def setupUi(self, UiForm):
        UiForm.setObjectName("UiForm")
        UiForm.resize(1024, 720)
        UiForm.setMinimumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(UiForm)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = PolygonSurface(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 1001, 651))
        self.widget.setObjectName("widget")
        UiForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UiForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 24))
        self.menubar.setObjectName("menubar")
        UiForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UiForm)
        self.statusbar.setObjectName("statusbar")
        UiForm.setStatusBar(self.statusbar)

        self.retranslateUi(UiForm)
        QtCore.QMetaObject.connectSlotsByName(UiForm)

    def retranslateUi(self, UiForm):
        _translate = QtCore.QCoreApplication.translate
        UiForm.setWindowTitle(_translate("UiForm", "Polygon Editor"))
from polygon_surface import PolygonSurface
