# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\ui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(274, 202)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(-90, 160, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(SettingsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 131, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bresenham_radio_button = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.bresenham_radio_button.setChecked(True)
        self.bresenham_radio_button.setObjectName("bresenham_radio_button")
        self.button_group = QtWidgets.QButtonGroup(SettingsDialog)
        self.button_group.setObjectName("button_group")
        self.button_group.addButton(self.bresenham_radio_button)
        self.verticalLayout.addWidget(self.bresenham_radio_button)
        self.wu_radio_button = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.wu_radio_button.setObjectName("wu_radio_button")
        self.button_group.addButton(self.wu_radio_button)
        self.verticalLayout.addWidget(self.wu_radio_button)
        self.qt_radio_button = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.qt_radio_button.setObjectName("qt_radio_button")
        self.button_group.addButton(self.qt_radio_button)
        self.verticalLayout.addWidget(self.qt_radio_button)
        self.label = QtWidgets.QLabel(SettingsDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.bresenham_radio_button.setText(_translate("SettingsDialog", "Bresenham"))
        self.wu_radio_button.setText(_translate("SettingsDialog", "Wu"))
        self.qt_radio_button.setText(_translate("SettingsDialog", "Qt Library"))
        self.label.setText(_translate("SettingsDialog", "Check drawing line algorithm:"))
